version: 2

models:
  - name: patient_claim_summary
    description: model with one record per claim for claims billed at least once
    columns:
      - name: claim_id
        tests:
          - unique
          - not_null
  - name: claim_diagnosis
    description: staging
    columns:
      - name: claim_id
        tests:
          - unique
          - not_null